trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: PowerShell@2
  displayName: 'Install PowerShell module from Azure DevOps Artifacts'
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = 'Stop'
      $moduleName = "KpInfo"
      
      # Ensure the module is not already installed
      if (!(Get-Module -ListAvailable -Name $moduleName)) {
          # Save the NuGet package containing the module to a temporary folder
          $tempFolder = New-Item -ItemType Directory -Path (Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString()))
          $nugetConfigPath = "$(Build.Repository.LocalPath)\nuget.config"
          & "nuget.exe" install $moduleName -ExcludeVersion -OutputDirectory $tempFolder -ConfigFile $nugetConfigPath
          
          # Import the module from the saved NuGet package
          $moduleFolder = Get-ChildItem -Path $tempFolder -Directory | Select-Object -First 1
          $modulePath = Join-Path $moduleFolder.FullName "$moduleName.psm1"
          Import-Module -Name $modulePath -Verbose
      }

      Get-CatFact

# - task: PowerShell@2
#   displayName: Install Module
#   name: installmodules
#   inputs:
#     pwsh: true
#     targetType: filePath
#     filePath: $(Build.SourcesDirectory)/Install-Module.ps1
#     argument: >
#       -pathNuget : '$(Build.SourcesDirectory)'

