trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: PowerShell@2
  displayName: Install Module
  name: installmodules
  inputs:
    pwsh: true
    targetType: filePath
    filePath: $(Build.SourcesDirectory)/Install-Module-Pat.ps1
