trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: PowerShell@2
  displayName: Install Module
  name: installmodules
  inputs:
    targetType: filePath
    filePath: $(Build.SourcesDirectory)/Install-Module.ps1
    arguments: > 
      -accessToken $env:SYSTEM_ACCESSTOKEN
      -moduleName 'KpInfo'
      -sourceName 'PsModuleTest'
      -feedLocation 'https://pkgs.dev.azure.com/xulongjunfr/LongjunTest/_packaging/PsModuleTest/nuget/v2'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken) #10

